#!/usr/bin/env python3
"""Replay libosmocore-generated bytes and check workbench mode behavior."""

import argparse
import json
import socket
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path


def http_json(base, path, method="GET", payload=None):
    body = None if payload is None else json.dumps(payload).encode()
    request = urllib.request.Request(
        base + path,
        data=body,
        method=method,
        headers={"Content-Type": "application/json"} if body else {},
    )
    try:
        with urllib.request.urlopen(request, timeout=3) as response:
            return response.status, json.load(response)
    except urllib.error.HTTPError as error:
        detail = error.read().decode(errors="replace")
        raise RuntimeError(f"HTTP {error.code} {path}: {detail}") from error


def wait_for_status(base, minimum, timeout=15):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            _, status = http_json(base, "/api/status")
            if status["stats"]["received"] >= minimum:
                return status
        except (OSError, RuntimeError, ValueError):
            pass
        time.sleep(0.1)
    raise RuntimeError(f"workbench did not receive {minimum} packets")


def workbench_status(base):
    _, status = http_json(base, "/api/status")
    return status


def load_vectors(directory):
    vectors = []
    for path in sorted(Path(directory).glob("*.json")):
        item = json.loads(path.read_text())
        try:
            vectors.append((path.name, bytes.fromhex(item["encoded_hex"])))
        except (KeyError, ValueError) as error:
            raise RuntimeError(f"invalid reference vector {path}: {error}") from error
    if not vectors:
        raise RuntimeError(f"no reference vectors found in {directory}")
    return vectors


def send_packets(host, port, packets, rounds):
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sender:
        for _ in range(rounds):
            for packet in packets:
                sender.sendto(packet, (host, port))


def collect_packets(sock, expected, timeout=5):
    sock.settimeout(0.2)
    packets = []
    deadline = time.monotonic() + timeout
    while len(packets) < expected and time.monotonic() < deadline:
        try:
            packets.append(sock.recvfrom(65535)[0])
        except socket.timeout:
            continue
    return packets


def first_decoded(records):
    return next((packet for packet in records if packet.get("decoded")), None)


def modify_payload(decoded):
    payload = {name: decoded[name] for name in (
        "version", "headerLengthWords", "messageType", "timeslot", "arfcn",
        "signalDbm", "snrDb", "frameNumber", "subtype", "antennaNumber",
        "subSlot", "reserved", "extensionHex", "payloadHex")}
    payload["arfcn"] = (payload["arfcn"] + 1) % 65536
    return payload


def check(args, vectors):
    base = f"http://{args.workbench_host}:{args.workbench_port}"
    initial_status = workbench_status(base)
    if initial_status["mode"] != args.mode:
        raise RuntimeError(
            f"workbench mode is {initial_status['mode']!r}, expected {args.mode!r}; "
            "restart it with the matching --mode"
        )
    source = [packet for _, packet in vectors]
    rounds = args.rounds
    # Include a deliberately malformed datagram in every mode so the UI's
    # parse-error filter can be verified alongside successful decodes.
    source.append(bytes.fromhex("deadbeef"))
    expected = len(source) * rounds
    received_before = initial_status["stats"]["received"]
    forwarded_before = initial_status["stats"].get("forwardSent", 0)
    forward_failures_before = initial_status["stats"].get("forwardFailed", 0)
    sink = None
    if args.mode in ("listen", "relay"):
        if not args.sink_port:
            raise RuntimeError("--sink-port is required for relay and modify")
        sink = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sink.bind(("0.0.0.0", args.sink_port))
    send_packets(args.workbench_host, args.listen_port, source, rounds)
    status = wait_for_status(base, received_before + expected)
    _, records = http_json(base, f"/api/packets?limit={max(expected, 500)}")
    if len(records) < expected:
        raise RuntimeError(f"API returned {len(records)} records, expected at least {expected}")
    parse_errors = sum(1 for record in records if record.get("parseError"))
    if parse_errors < rounds:
        raise RuntimeError(f"API returned {parse_errors} parse errors, expected at least {rounds}")

    if args.mode == "listen":
        if status["stats"]["received"] < expected:
            raise RuntimeError("listen mode receive accounting is short")
        if collect_packets(sink, 1, timeout=0.5):
            raise RuntimeError("listen mode forwarded a packet to the configured sink")
        sink.close()
        print(f"listen: received {expected} datagrams including {parse_errors} parse errors; configured sink received none")
        return

    if not args.sink_port:
        raise RuntimeError("--sink-port is required for relay and modify")
    if args.mode == "relay":
        forwarded = status["stats"].get("forwardSent", 0) - forwarded_before
        forward_failures = status["stats"].get("forwardFailed", 0) - forward_failures_before
        if forwarded != expected:
            raise RuntimeError(
                f"relay received {expected} new datagrams but forwarded {forwarded}; "
                f"{forward_failures} forwarding failures reported. "
                f"Configured target is {status.get('gsmtapForward')!r}."
            )
        with sink:
            received = collect_packets(sink, expected)
        if received != source * rounds:
            raise RuntimeError(
                f"relay sent {forwarded} datagrams but the local sink received {len(received)}, "
                f"expected {expected}. Configured target is {status.get('gsmtapForward')!r}; "
                "ensure it points to this machine's UDP sink port."
            )
        print(f"relay: forwarded {expected} datagrams byte-for-byte, including deadbeef")
        return

    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sink:
        sink.bind(("0.0.0.0", args.sink_port))
        packet = first_decoded(records)
        if not packet:
            raise RuntimeError("modify mode found no decoded retained packet")
        packet_id = packet["id"]
        payload = modify_payload(packet["decoded"])
        invalid_payload = dict(payload)
        invalid_payload["headerLengthWords"] = 5
        try:
            http_json(base, f"/api/packets/{packet_id}/modify-send", "POST", invalid_payload)
        except RuntimeError:
            pass
        else:
            raise RuntimeError("invalid modify-send unexpectedly succeeded")
        if collect_packets(sink, 1, timeout=0.5):
            raise RuntimeError("invalid modify-send sent a packet")
        status_code, preview = http_json(base, f"/api/packets/{packet_id}/modify-preview", "POST", payload)
        if status_code != 200 or preview["packetId"] != packet_id:
            raise RuntimeError("modify preview did not return the selected packet")
        if collect_packets(sink, 1, timeout=0.5):
            raise RuntimeError("modify preview sent a packet")
        _, replay = http_json(base, f"/api/packets/{packet_id}/replay", "POST")
        replayed = collect_packets(sink, 1)
        if replayed != [bytes.fromhex(packet["rawHex"])]:
            raise RuntimeError("modify replay did not send original bytes")
        _, modified = http_json(base, f"/api/packets/{packet_id}/modify-send", "POST", payload)
        changed = collect_packets(sink, 1)
        expected_changed = bytes.fromhex(modified["encodedHex"])
        if changed != [expected_changed] or changed[0] == replayed[0]:
            raise RuntimeError("modify-send did not send the changed encoded bytes")
        _, final_records = http_json(base, f"/api/packets?limit=1000")
        if not any(record.get("modified") and record.get("originalRawHex") and record.get("finalRawHex") for record in final_records):
            raise RuntimeError("modify history did not retain original and final bytes")
        print(f"modify: preview was side-effect free; replay and changed send verified for #{packet_id}")


def main(default_mode=None):
    parser = argparse.ArgumentParser()
    if default_mode is None:
        parser.add_argument("--mode", choices=("listen", "relay", "modify"), required=True)
    parser.add_argument("--workbench-host", required=True)
    parser.add_argument("--workbench-port", type=int, default=8080)
    parser.add_argument("--listen-port", type=int, default=4729)
    parser.add_argument("--sink-port", type=int)
    parser.add_argument("--vectors", default="/opt/traffic/vectors")
    parser.add_argument("--rounds", type=int, default=1)
    args = parser.parse_args()
    args.mode = default_mode or args.mode
    if args.rounds < 1:
        parser.error("--rounds must be positive")
    try:
        check(args, load_vectors(args.vectors))
    except (OSError, RuntimeError, ValueError) as error:
        print(f"traffic test failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
